import type { FoodInfoData } from '../food.ts';

export const allFoodInfos = [
  {
    id: 'rice',
    name: '米',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'rice',
  },
  {
    id: 'egg',
    name: '卵',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'egg',
  },
  {
    id: 'milk',
    name: '牛乳',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'milk',
  },
  {
    id: 'bread',
    name: '食パン',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'bread',
  },
  {
    id: 'beef',
    name: '牛肉',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'beef',
  },
  {
    id: 'chicken',
    name: '鶏肉',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'chicken',
  },
  {
    id: 'shrimp',
    name: 'エビ',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'shrimp',
  },
  {
    id: 'potato',
    name: 'ジャガイモ',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'potato',
  },
  {
    id: 'carrot',
    name: 'ニンジン',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'carrot',
  },
  {
    id: 'onion',
    name: '玉ねぎ',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'onion',
  },
  {
    id: 'tomato',
    name: 'トマト',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'tomato',
  },
  {
    id: 'lettuce',
    name: 'レタス',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'lettuce',
  },
  {
    id: 'cheese',
    name: 'チーズ',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'cheese',
  },
  {
    id: 'curry-powder',
    name: 'カレー粉',
    ingredientIds: [],
    process: null,
    canSpawnFromStorage: true,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'curry-powder',
  },
  {
    id: 'sliced-tomato',
    name: 'スライストマト',
    ingredientIds: ['tomato'],
    process: 'cutting',
    canSpawnFromStorage: false,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'sliced-tomato',
  },
  {
    id: 'chopped-onion',
    name: '刻み玉ねぎ',
    ingredientIds: ['onion'],
    process: 'cutting',
    canSpawnFromStorage: false,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'chopped-onion',
  },
  {
    id: 'chopped-lettuce',
    name: '刻みレタス',
    ingredientIds: ['lettuce'],
    process: 'cutting',
    canSpawnFromStorage: false,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'chopped-lettuce',
  },
  {
    id: 'cut-potato',
    name: 'ポテト',
    ingredientIds: ['potato'],
    process: 'cutting',
    canSpawnFromStorage: false,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'cut-potato',
  },
  {
    id: 'cooked-beef',
    name: '炒め肉',
    ingredientIds: ['beef'],
    process: 'heating',
    canSpawnFromStorage: false,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'cooked-beef',
  },
  {
    id: 'grilled-chicken',
    name: 'グリルチキン',
    ingredientIds: ['chicken'],
    process: 'heating',
    canSpawnFromStorage: false,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'grilled-chicken',
  },
  {
    id: 'prepared-shrimp',
    name: '下処理エビ',
    ingredientIds: ['shrimp'],
    process: 'cutting',
    canSpawnFromStorage: false,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'prepared-shrimp',
  },
  {
    id: 'chopped-carrot',
    name: '刻みニンジン',
    ingredientIds: ['carrot'],
    process: 'cutting',
    canSpawnFromStorage: false,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'chopped-carrot',
  },
  {
    id: 'tomato-sauce',
    name: 'トマトソース',
    ingredientIds: ['sliced-tomato'],
    process: 'mixing',
    canSpawnFromStorage: false,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'tomato-sauce',
  },
  {
    id: 'boiled-egg',
    name: 'ゆで卵',
    ingredientIds: ['egg'],
    process: 'heating',
    canSpawnFromStorage: false,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'boiled-egg',
  },
  {
    id: 'curry-sauce',
    name: 'カレーソース',
    ingredientIds: ['curry-powder', 'chopped-onion', 'chopped-carrot'],
    process: 'mixing',
    canSpawnFromStorage: false,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'curry-sauce',
  },
  {
    id: 'omelet-base',
    name: 'オムレツのもと',
    ingredientIds: ['egg', 'milk', 'cheese'],
    process: 'mixing',
    canSpawnFromStorage: false,
    canBeServed: false,
    canBeIngredient: true,
    difficulty: null,
    spriteId: 'omelet-base',
  },
  {
    id: 'cooked-rice',
    name: 'ごはん',
    ingredientIds: ['rice'],
    process: 'heating',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: true,
    difficulty: 1,
    spriteId: 'cooked-rice',
  },
  {
    id: 'toast',
    name: 'トースト',
    ingredientIds: ['bread'],
    process: 'heating',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: true,
    difficulty: 1,
    spriteId: 'toast',
  },
  {
    id: 'fried-egg',
    name: '目玉焼き',
    ingredientIds: ['egg'],
    process: 'heating',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: true,
    difficulty: 1,
    spriteId: 'fried-egg',
  },
  {
    id: 'french-fries',
    name: 'ポテトフライ',
    ingredientIds: ['cut-potato'],
    process: 'heating',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: true,
    difficulty: 1,
    spriteId: 'french-fries',
  },
  {
    id: 'salad',
    name: 'サラダ',
    ingredientIds: ['chopped-lettuce', 'sliced-tomato'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: true,
    difficulty: 1,
    spriteId: 'salad',
  },
  {
    id: 'beef-steak',
    name: 'ビーフステーキ',
    ingredientIds: ['cooked-beef'],
    process: 'cutting',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: true,
    difficulty: 1,
    spriteId: 'beef-steak',
  },
  {
    id: 'chicken-saute',
    name: 'チキンソテー',
    ingredientIds: ['grilled-chicken', 'french-fries'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: true,
    difficulty: 1,
    spriteId: 'chicken-saute',
  },
  {
    id: 'cheese-toast',
    name: 'チーズトースト',
    ingredientIds: ['toast', 'cheese'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 1,
    spriteId: 'cheese-toast',
  },
  {
    id: 'potato-salad',
    name: 'ポテトサラダ',
    ingredientIds: ['cut-potato', 'chopped-carrot'],
    process: 'mixing',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 1,
    spriteId: 'potato-salad',
  },
  {
    id: 'fried-egg-toast',
    name: '目玉焼きトースト',
    ingredientIds: ['toast', 'lettuce', 'fried-egg'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 2,
    spriteId: 'fried-egg-toast',
  },
  {
    id: 'egg-sandwich',
    name: '卵サンド',
    ingredientIds: ['bread', 'boiled-egg', 'chopped-lettuce'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 2,
    spriteId: 'egg-sandwich',
  },
  {
    id: 'omelet',
    name: 'オムレツ',
    ingredientIds: ['omelet-base'],
    process: 'heating',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: true,
    difficulty: 2,
    spriteId: 'omelet',
  },
  {
    id: 'chicken-salad',
    name: 'チキンサラダ',
    ingredientIds: ['grilled-chicken', 'salad'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 2,
    spriteId: 'chicken-salad',
  },
  {
    id: 'shrimp-salad',
    name: 'エビサラダ',
    ingredientIds: ['prepared-shrimp', 'salad'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 2,
    spriteId: 'shrimp-salad',
  },
  {
    id: 'beef-tomato-stew',
    name: '牛肉のトマト煮',
    ingredientIds: ['cooked-beef', 'tomato-sauce', 'chopped-onion'],
    process: 'heating',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 2,
    spriteId: 'beef-tomato-stew',
  },
  {
    id: 'chicken-tomato-stew',
    name: 'チキントマト煮',
    ingredientIds: ['grilled-chicken', 'tomato-sauce', 'chopped-onion'],
    process: 'heating',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 2,
    spriteId: 'chicken-tomato-stew',
  },
  {
    id: 'mixed-grill',
    name: 'ミックスグリル',
    ingredientIds: ['beef-steak', 'chicken-saute'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 2,
    spriteId: 'mixed-grill',
  },
  {
    id: 'tomato-cheese-sandwich',
    name: 'トマトチーズサンド',
    ingredientIds: ['bread', 'sliced-tomato', 'cheese'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 2,
    spriteId: 'tomato-cheese-sandwich',
  },
  {
    id: 'shrimp-omelet',
    name: 'エビオムレツ',
    ingredientIds: ['prepared-shrimp', 'omelet-base'],
    process: 'heating',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 3,
    spriteId: 'shrimp-omelet',
  },
  {
    id: 'hamburg',
    name: 'ハンバーグ',
    ingredientIds: [
      'beef',
      'chopped-onion',
      'egg',
      'bread',
      'tomato-sauce',
      'milk',
    ],
    process: 'heating',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 3,
    spriteId: 'hamburg',
  },
  {
    id: 'curry-rice',
    name: 'カレーライス',
    ingredientIds: ['cooked-rice', 'cooked-beef', 'curry-sauce'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 3,
    spriteId: 'curry-rice',
  },
  {
    id: 'omurice',
    name: 'オムライス',
    ingredientIds: ['cooked-rice', 'grilled-chicken', 'tomato-sauce', 'omelet'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 3,
    spriteId: 'omurice',
  },
  {
    id: 'fried-rice',
    name: 'チャーハン',
    ingredientIds: ['cooked-rice', 'egg', 'chopped-onion', 'chopped-carrot'],
    process: 'mixing',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 3,
    spriteId: 'fried-rice',
  },
  {
    id: 'shrimp-pilaf',
    name: 'エビピラフ',
    ingredientIds: [
      'cooked-rice',
      'prepared-shrimp',
      'chopped-onion',
      'chopped-carrot',
    ],
    process: 'mixing',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 3,
    spriteId: 'shrimp-pilaf',
  },
  {
    id: 'cheese-curry',
    name: 'チーズカレー',
    ingredientIds: ['cooked-rice', 'cut-potato', 'cheese', 'curry-sauce'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 3,
    spriteId: 'cheese-curry',
  },
  {
    id: 'chicken-curry',
    name: 'チキンカレー',
    ingredientIds: ['cooked-rice', 'grilled-chicken', 'curry-sauce'],
    process: 'combining',
    canSpawnFromStorage: false,
    canBeServed: true,
    canBeIngredient: false,
    difficulty: 3,
    spriteId: 'chicken-curry',
  },
] as const satisfies readonly FoodInfoData[];
