services:
  web:
    build:
      context: .
      dockerfile: .docker/web/local.Dockerfile
      args:
        - BASE_IMAGE=node:24.16.0-slim
        - PNPM_VERSION=11.5.2
    volumes:
      - type: bind
        source: ./apps
        target: /workspace/apps
      - type: volume
        source: pnpm_store
        target: /home/node/.local/share/pnpm/store
    working_dir: /workspace/apps
    command: sleep infinity
    init: true

volumes:
  pnpm_store:
