import type { FoodModelData } from '../food.ts';

export const boiledEggFoodModel = {
  schemaVersion: 'food-model-v1',
  id: 'boiled-egg',
  displayName: 'ゆで卵',
  category: 'intermediate',
  frontDirection: '-Z',
  unitScale: 1,
  pivot: [0, 0.32, 0],
  bounds: { size: [1.04, 0.64, 0.72], center: [0, 0.32, 0] },
  parts: [
    {
      id: 'left-white',
      shape: 'sphere',
      position: [-0.25, 0.32, 0],
      size: [0.52, 0.56, 0.62],
      rotation: [0, 0, -0.2],
      color: '#FFF7E8',
      material: { roughness: 0.86, metalness: 0 },
      appearance: { radius: 0.12, segments: 8, flatShading: false },
    },
    {
      id: 'right-white',
      shape: 'sphere',
      position: [0.25, 0.32, 0],
      size: [0.52, 0.56, 0.62],
      rotation: [0, 0, 0.2],
      color: '#FFF7E8',
      material: { roughness: 0.86, metalness: 0 },
      appearance: { radius: 0.12, segments: 8, flatShading: false },
    },
    {
      id: 'left-yolk',
      shape: 'sphere',
      position: [-0.25, 0.34, -0.31],
      size: [0.24, 0.24, 0.08],
      rotation: [0, 0, 0],
      color: '#F3B332',
      material: { roughness: 0.82, metalness: 0 },
      appearance: { radius: 0.05, segments: 8, flatShading: false },
    },
    {
      id: 'right-yolk',
      shape: 'sphere',
      position: [0.25, 0.34, -0.31],
      size: [0.24, 0.24, 0.08],
      rotation: [0, 0, 0],
      color: '#F3B332',
      material: { roughness: 0.82, metalness: 0 },
      appearance: { radius: 0.05, segments: 8, flatShading: false },
    },
    {
      id: 'cut-shadow',
      shape: 'roundedBox',
      position: [0, 0.12, -0.25],
      size: [0.82, 0.08, 0.08],
      rotation: [0, 0, 0],
      color: '#EADCC8',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.03, segments: 4, flatShading: false },
    },
  ],
  designNotes: [
    '半割り卵が並ぶ形にして、白身と黄身を正面から読ませる。',
    '黄身は前面の浅い球で表現し、薄い影で切断面の接地感を出す。',
    '食材として使う中間素材なので皿は置かず、卵本体だけにする。',
  ],
} as const satisfies FoodModelData;
