import type { FoodModelData } from '../food.ts';

export const cookedRiceFoodModel = {
  schemaVersion: 'food-model-v1',
  id: 'cooked-rice',
  displayName: 'ごはん',
  category: 'dish',
  frontDirection: '-Z',
  unitScale: 1,
  pivot: [0, 0.42, 0],
  bounds: { size: [1.18, 0.84, 1], center: [0, 0.42, 0] },
  parts: [
    {
      id: 'bowl',
      shape: 'cylinder',
      position: [0, 0.18, 0],
      size: [1.0, 0.28, 0.82],
      rotation: [0, 0, 0],
      color: '#D9EEF3',
      material: { roughness: 0.84, metalness: 0 },
      appearance: { radius: 0.06, segments: 12, flatShading: false },
    },
    {
      id: 'bowl-rim',
      shape: 'cylinder',
      position: [0, 0.34, 0],
      size: [1.08, 0.1, 0.9],
      rotation: [0, 0, 0],
      color: '#F8FAFC',
      material: { roughness: 0.82, metalness: 0 },
      appearance: { radius: 0.05, segments: 12, flatShading: false },
    },
    {
      id: 'rice-mound',
      shape: 'sphere',
      position: [0, 0.56, -0.02],
      size: [0.86, 0.54, 0.72],
      rotation: [0, 0, 0],
      color: '#F7F1DE',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.12, segments: 8, flatShading: false },
    },
    {
      id: 'rice-grain-left',
      shape: 'roundedBox',
      position: [-0.24, 0.68, -0.34],
      size: [0.18, 0.06, 0.05],
      rotation: [0, 0, 0.22],
      color: '#E7D6B7',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.02, segments: 4, flatShading: false },
    },
    {
      id: 'rice-grain-right',
      shape: 'roundedBox',
      position: [0.22, 0.6, -0.34],
      size: [0.16, 0.05, 0.05],
      rotation: [0, 0, -0.25],
      color: '#E7D6B7',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.02, segments: 4, flatShading: false },
    },
  ],
  designNotes: [
    '茶碗と白い山形のご飯を大きく配置し、完成料理として読みやすくする。',
    '前面に少数の米粒アクセントを置き、米俵の素材モデルと区別する。',
    '白と淡い水色の対比で、皿ではなく茶碗に盛ったご飯に見せる。',
  ],
} as const satisfies FoodModelData;
