import type { FoodModelData } from '../food.ts';

export const friedEggFoodModel = {
  schemaVersion: 'food-model-v1',
  id: 'fried-egg',
  displayName: '目玉焼き',
  category: 'dish',
  frontDirection: '-Z',
  unitScale: 1,
  pivot: [0, 0.09, 0],
  bounds: { size: [1.18, 0.18, 0.92], center: [0, 0.09, 0] },
  parts: [
    {
      id: 'white-main',
      shape: 'sphere',
      position: [0, 0.08, 0],
      size: [1.0, 0.12, 0.72],
      rotation: [0, 0, 0],
      color: '#FFF8EC',
      material: { roughness: 0.86, metalness: 0 },
      appearance: { radius: 0.1, segments: 8, flatShading: false },
    },
    {
      id: 'white-lobe-left',
      shape: 'sphere',
      position: [-0.33, 0.08, -0.02],
      size: [0.52, 0.1, 0.44],
      rotation: [0, 0, 0.2],
      color: '#FFFDF7',
      material: { roughness: 0.86, metalness: 0 },
      appearance: { radius: 0.08, segments: 8, flatShading: false },
    },
    {
      id: 'white-lobe-right',
      shape: 'sphere',
      position: [0.36, 0.08, 0.04],
      size: [0.5, 0.1, 0.4],
      rotation: [0, 0, -0.16],
      color: '#FFFDF7',
      material: { roughness: 0.86, metalness: 0 },
      appearance: { radius: 0.08, segments: 8, flatShading: false },
    },
    {
      id: 'yolk',
      shape: 'sphere',
      position: [0.02, 0.16, -0.08],
      size: [0.34, 0.22, 0.34],
      rotation: [0, 0, 0],
      color: '#F4B431',
      material: { roughness: 0.78, metalness: 0 },
      appearance: { radius: 0.08, segments: 8, flatShading: false },
    },
    {
      id: 'yolk-highlight',
      shape: 'sphere',
      position: [-0.06, 0.22, -0.2],
      size: [0.1, 0.05, 0.06],
      rotation: [0, 0, 0],
      color: '#FFD875',
      material: { roughness: 0.82, metalness: 0 },
      appearance: { radius: 0.03, segments: 6, flatShading: false },
    },
  ],
  designNotes: [
    '低い白身の円盤と中央の黄身で、目玉焼きの記号性を優先する。',
    '白身を複数の浅い球で崩し、自然な広がりを軽量に表現する。',
    '黄身の小さなハイライトで前面からの視認性を高める。',
  ],
} as const satisfies FoodModelData;
