import type { FoodModelData } from '../food.ts';

export const milkFoodModel = {
  schemaVersion: 'food-model-v1',
  id: 'milk',
  displayName: '牛乳',
  category: 'ingredient',
  frontDirection: '-Z',
  unitScale: 1,
  bounds: { size: [0.78, 1.32, 0.58], center: [0, 0.66, 0] },
  parts: [
    {
      id: 'carton-body',
      shape: 'roundedBox',
      position: [0, 0.55, 0],
      size: [0.66, 1.02, 0.46],
      rotation: [0, 0, 0],
      color: '#FFFDF9',
      material: { roughness: 0.82, metalness: 0 },
      appearance: { radius: 0.06, segments: 4, flatShading: false },
    },
    {
      id: 'gable-front',
      shape: 'roundedBox',
      position: [0, 1.13, -0.08],
      size: [0.64, 0.24, 0.24],
      rotation: [0.44, 0, 0],
      color: '#F1F6FF',
      material: { roughness: 0.84, metalness: 0 },
      appearance: { radius: 0.04, segments: 4, flatShading: false },
    },
    {
      id: 'gable-back',
      shape: 'roundedBox',
      position: [0, 1.13, 0.08],
      size: [0.64, 0.24, 0.24],
      rotation: [-0.44, 0, 0],
      color: '#E2ECFA',
      material: { roughness: 0.86, metalness: 0 },
      appearance: { radius: 0.04, segments: 4, flatShading: false },
    },
    {
      id: 'top-ridge',
      shape: 'roundedBox',
      position: [0, 1.26, 0],
      size: [0.58, 0.08, 0.12],
      rotation: [0, 0, 0],
      color: '#D8E7F8',
      material: { roughness: 0.88, metalness: 0 },
      appearance: { radius: 0.03, segments: 4, flatShading: false },
    },
    {
      id: 'blue-label',
      shape: 'roundedBox',
      position: [0, 0.62, -0.26],
      size: [0.52, 0.34, 0.05],
      rotation: [0, 0, 0],
      color: '#5B9BD5',
      material: { roughness: 0.86, metalness: 0 },
      appearance: { radius: 0.04, segments: 4, flatShading: false },
    },
    {
      id: 'label-window',
      shape: 'roundedBox',
      position: [0, 0.62, -0.29],
      size: [0.3, 0.14, 0.04],
      rotation: [0, 0, 0],
      color: '#FFFFFF',
      material: { roughness: 0.84, metalness: 0 },
      appearance: { radius: 0.03, segments: 4, flatShading: false },
    },
    {
      id: 'milk-drop',
      shape: 'sphere',
      position: [0, 0.79, -0.3],
      size: [0.12, 0.18, 0.05],
      rotation: [0, 0, 0],
      color: '#FFFFFF',
      material: { roughness: 0.82, metalness: 0 },
      appearance: { radius: 0.04, segments: 6, flatShading: false },
    },
  ],
  designNotes: [
    '白い紙パック本体と屋根型トップで、牛乳パックのシルエットを優先する。',
    '青いラベル帯と白いしずくで、牛乳らしい清潔感と識別性を出す。',
    '薄い奥行きのラベル部品だけを前面に置き、汎用プリミティブで軽量に保つ。',
  ],
} as const satisfies FoodModelData;
