import type { FoodModelData } from '../food.ts';

export const riceFoodModel = {
  schemaVersion: 'food-model-v1',
  id: 'rice',
  displayName: '米',
  category: 'ingredient',
  frontDirection: '-Z',
  unitScale: 1,
  bounds: { size: [0.86, 1.18, 0.5], center: [0, 0.59, 0] },
  parts: [
    {
      id: 'bag-body',
      shape: 'roundedBox',
      position: [0, 0.52, 0],
      size: [0.78, 0.96, 0.42],
      rotation: [0, 0, 0],
      color: '#F4EAD2',
      material: { roughness: 0.88, metalness: 0 },
      appearance: { radius: 0.1, segments: 6, flatShading: false },
    },
    {
      id: 'folded-top',
      shape: 'roundedBox',
      position: [0, 1.04, -0.01],
      size: [0.72, 0.18, 0.38],
      rotation: [0, 0, 0],
      color: '#E7D6B7',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.07, segments: 4, flatShading: false },
    },
    {
      id: 'front-label',
      shape: 'roundedBox',
      position: [0, 0.58, -0.24],
      size: [0.48, 0.34, 0.05],
      rotation: [0, 0, 0],
      color: '#FFFFFF',
      material: { roughness: 0.86, metalness: 0 },
      appearance: { radius: 0.04, segments: 4, flatShading: false },
    },
    {
      id: 'label-band',
      shape: 'roundedBox',
      position: [0, 0.72, -0.27],
      size: [0.38, 0.06, 0.04],
      rotation: [0, 0, 0],
      color: '#A77B43',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.02, segments: 4, flatShading: false },
    },
    {
      id: 'rice-grain-left',
      shape: 'capsule',
      position: [-0.1, 0.5, -0.29],
      size: [0.08, 0.2, 0.08],
      rotation: [0, 0, 0.6],
      color: '#FFFDF9',
      material: { roughness: 0.88, metalness: 0 },
      appearance: { radius: 0.03, segments: 6, flatShading: false },
    },
    {
      id: 'rice-grain-right',
      shape: 'capsule',
      position: [0.1, 0.48, -0.29],
      size: [0.08, 0.2, 0.08],
      rotation: [0, 0, -0.55],
      color: '#FFFDF9',
      material: { roughness: 0.88, metalness: 0 },
      appearance: { radius: 0.03, segments: 6, flatShading: false },
    },
  ],
  designNotes: [
    'ユーザー指定に合わせ、米粒そのものではなく米袋として表現する。',
    '生成りの袋本体と白い正面ラベルで、食品倉庫の基本素材として読みやすくする。',
    '小さな米粒マークを正面に置き、袋の中身が米だと分かるようにする。',
  ],
} as const satisfies FoodModelData;
