import type { FoodModelData } from '../food.ts';

export const riceFoodModel = {
  schemaVersion: 'food-model-v1',
  id: 'rice',
  displayName: '米',
  category: 'ingredient',
  frontDirection: '-Z',
  unitScale: 1,
  pivot: [0, 0.38, 0],
  bounds: { size: [1.2, 0.76, 0.76], center: [0, 0.38, 0] },
  parts: [
    {
      id: 'straw-barrel',
      shape: 'cylinder',
      position: [0, 0.38, 0],
      size: [0.74, 1, 0.74],
      rotation: [0, 0, 1.57],
      color: '#BDB76B',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.08, segments: 12, flatShading: false },
    },
    {
      id: 'left-end',
      shape: 'sphere',
      position: [-0.5, 0.38, 0],
      size: [0.74, 0.44, 0.74],
      rotation: [0, 0, 1.57],
      color: '#BDB76B',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.08, segments: 12, flatShading: false },
    },
    {
      id: 'rope-left-hori',
      shape: 'cylinder',
      position: [-0.52, 0.38, 0],
      size: [0.44, 0.04, 0.74],
      rotation: [1.57, 0, 0],
      color: '#D1C169',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.08, segments: 12, flatShading: false },
    },
    {
      id: 'rope-left-vert',
      shape: 'cylinder',
      position: [-0.52, 0.38, 0],
      size: [0.44, 0.04, 0.74],
      rotation: [0, 0, 0],
      color: '#D1C169',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.08, segments: 12, flatShading: false },
    },
    {
      id: 'right-end',
      shape: 'sphere',
      position: [0.5, 0.38, 0],
      size: [0.74, 0.44, 0.74],
      rotation: [0, 0, 1.57],
      color: '#BDB76B',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.08, segments: 12, flatShading: false },
    },
    {
      id: 'rope-right-hori',
      shape: 'cylinder',
      position: [0.52, 0.38, 0],
      size: [0.44, 0.04, 0.74],
      rotation: [1.57, 0, 0],
      color: '#D1C169',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.08, segments: 12, flatShading: false },
    },
    {
      id: 'rope-right-vert',
      shape: 'cylinder',
      position: [0.52, 0.38, 0],
      size: [0.44, 0.04, 0.74],
      rotation: [0, 0, 0],
      color: '#D1C169',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.08, segments: 12, flatShading: false },
    },
    {
      id: 'rope-hori1',
      shape: 'roundedBox',
      position: [0, 0.73, 0],
      size: [1.14, 0.05, 0.05],
      rotation: [0, 0, 0],
      color: '#D1C169',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.02, segments: 4, flatShading: false },
    },
    {
      id: 'rope-hori2',
      shape: 'roundedBox',
      position: [0, 0.38, -0.35],
      size: [1.14, 0.05, 0.05],
      rotation: [0, 0, 0],
      color: '#D1C169',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.02, segments: 4, flatShading: false },
    },
    {
      id: 'rope-hori3',
      shape: 'roundedBox',
      position: [0, 0.03, 0],
      size: [1.14, 0.05, 0.05],
      rotation: [0, 0, 0],
      color: '#D1C169',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.02, segments: 4, flatShading: false },
    },
    {
      id: 'rope-hori4',
      shape: 'roundedBox',
      position: [0, 0.38, 0.35],
      size: [1.14, 0.05, 0.05],
      rotation: [0, 0, 0],
      color: '#D1C169',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.02, segments: 4, flatShading: false },
    },
    {
      id: 'rope-vert1',
      shape: 'cylinder',
      position: [-0.5, 0.38, 0],
      size: [0.76, 0.05, 0.76],
      rotation: [0, 0, 1.57],
      color: '#D1C169',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.08, segments: 12, flatShading: false },
    },
    {
      id: 'rope-vert2',
      shape: 'cylinder',
      position: [-0.16, 0.38, 0],
      size: [0.76, 0.05, 0.76],
      rotation: [0, 0, 1.57],
      color: '#D1C169',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.08, segments: 12, flatShading: false },
    },
    {
      id: 'rope-vert3',
      shape: 'cylinder',
      position: [0.16, 0.38, 0],
      size: [0.76, 0.05, 0.76],
      rotation: [0, 0, 1.57],
      color: '#D1C169',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.08, segments: 12, flatShading: false },
    },
    {
      id: 'rope-vert4',
      shape: 'cylinder',
      position: [0.5, 0.38, 0],
      size: [0.76, 0.05, 0.76],
      rotation: [0, 0, 1.57],
      color: '#D1C169',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.08, segments: 12, flatShading: false },
    },
  ],
  designNotes: [
    'ユーザー指定に合わせ、米袋ではなく横倒しの米俵として表現する。',
    '黄土色の横向き円柱をベースにして、俵の丸い胴体を大きく読ませる。',
    '少し濃い黄土色の細い直方体を曲面の見える位置に置き、縄掛けを軽量に表現する。',
  ],
} as const satisfies FoodModelData;
