import type { FoodModelData } from '../food.ts';

export const riceFoodModel = {
  schemaVersion: 'food-model-v1',
  id: 'rice',
  displayName: '米',
  category: 'ingredient',
  frontDirection: '-Z',
  unitScale: 1,
  pivot: [0, 0.38, 0],
  bounds: { size: [1.2, 0.76, 0.76], center: [0, 0.38, 0] },
  parts: [
    {
      id: 'straw-barrel',
      shape: 'cylinder',
      position: [0, 0.38, 0],
      size: [0.74, 1.08, 0.74],
      rotation: [0, 0, 1.57],
      color: '#C8A04A',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.08, segments: 12, flatShading: false },
    },
    {
      id: 'left-end',
      shape: 'cylinder',
      position: [-0.56, 0.38, 0],
      size: [0.78, 0.04, 0.78],
      rotation: [0, 0, 1.57],
      color: '#B9903D',
      material: { roughness: 0.92, metalness: 0 },
      appearance: { radius: 0.04, segments: 12, flatShading: false },
    },
    {
      id: 'right-end',
      shape: 'cylinder',
      position: [0.56, 0.38, 0],
      size: [0.78, 0.04, 0.78],
      rotation: [0, 0, 1.57],
      color: '#B9903D',
      material: { roughness: 0.92, metalness: 0 },
      appearance: { radius: 0.04, segments: 12, flatShading: false },
    },
    {
      id: 'left-rope-top',
      shape: 'roundedBox',
      position: [-0.3, 0.72, 0],
      size: [0.06, 0.08, 0.7],
      rotation: [0, 0, 0],
      color: '#9B762F',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.02, segments: 4, flatShading: false },
    },
    {
      id: 'left-rope-front',
      shape: 'roundedBox',
      position: [-0.3, 0.38, -0.36],
      size: [0.06, 0.68, 0.08],
      rotation: [0, 0, 0],
      color: '#9B762F',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.02, segments: 4, flatShading: false },
    },
    {
      id: 'right-rope-top',
      shape: 'roundedBox',
      position: [0.3, 0.72, 0],
      size: [0.06, 0.08, 0.7],
      rotation: [0, 0, 0],
      color: '#9B762F',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.02, segments: 4, flatShading: false },
    },
    {
      id: 'right-rope-front',
      shape: 'roundedBox',
      position: [0.3, 0.38, -0.36],
      size: [0.06, 0.68, 0.08],
      rotation: [0, 0, 0],
      color: '#9B762F',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.02, segments: 4, flatShading: false },
    },
    {
      id: 'center-rope-front',
      shape: 'roundedBox',
      position: [0, 0.38, -0.37],
      size: [1.0, 0.07, 0.07],
      rotation: [0, 0, 0],
      color: '#9B762F',
      material: { roughness: 0.94, metalness: 0 },
      appearance: { radius: 0.02, segments: 4, flatShading: false },
    },
  ],
  designNotes: [
    'ユーザー指定に合わせ、米袋ではなく横倒しの米俵として表現する。',
    '黄土色の横向き円柱をベースにして、俵の丸い胴体を大きく読ませる。',
    '少し濃い黄土色の細い直方体を曲面の見える位置に置き、縄掛けを軽量に表現する。',
  ],
} as const satisfies FoodModelData;
