import type { FoodModelData } from '../food.ts';

export const toastFoodModel = {
  schemaVersion: 'food-model-v1',
  id: 'toast',
  displayName: 'トースト',
  category: 'dish',
  frontDirection: '-Z',
  unitScale: 1,
  pivot: [0, 0.54, 0],
  bounds: { size: [1.12, 1.08, 0.42], center: [0, 0.54, 0] },
  parts: [
    {
      id: 'crust-body',
      shape: 'roundedBox',
      position: [0, 0.54, 0],
      size: [1.08, 1.04, 0.36],
      rotation: [0, 0, 0],
      color: '#85511C',
      material: { roughness: 0.88, metalness: 0 },
      appearance: { radius: 0.1, segments: 6, flatShading: false },
    },
    {
      id: 'crust-head',
      shape: 'roundedBox',
      position: [0, 0.91, 0],
      size: [1.13, 0.3, 0.36],
      rotation: [0, 0, 0],
      color: '#85511C',
      material: { roughness: 0.88, metalness: 0 },
      appearance: { radius: 0.1, segments: 6, flatShading: false },
    },
    {
      id: 'soft-center',
      shape: 'roundedBox',
      position: [0, 0.54, 0],
      size: [1.04, 1.0, 0.38],
      rotation: [0, 0, 0],
      color: '#C79C6F',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.12, segments: 6, flatShading: false },
    },
    {
      id: 'soft-head',
      shape: 'roundedBox',
      position: [0, 0.9, 0],
      size: [1.07, 0.3, 0.38],
      rotation: [0, 0, 0],
      color: '#C79C6F',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.12, segments: 6, flatShading: false },
    },
  ],
  designNotes: [
    '食パンモデルと同じ一枚パンの外形を保ち、全体を焼き色に寄せて加工後と分かるようにする。',
    '中央を明るい黄金色にして、外側の濃い耳と焼き目を読みやすくする。',
    '前面の縦焼き目だけでトーストらしさを表現し、部品数を抑える。',
  ],
} as const satisfies FoodModelData;
