import type { FoodModelData } from '../food.ts';

export const toastFoodModel = {
  schemaVersion: 'food-model-v1',
  id: 'toast',
  displayName: 'トースト',
  category: 'dish',
  frontDirection: '-Z',
  unitScale: 1,
  pivot: [0, 0.52, 0],
  bounds: { size: [1.14, 1.04, 0.42], center: [0, 0.52, 0] },
  parts: [
    {
      id: 'toast-body',
      shape: 'roundedBox',
      position: [0, 0.52, 0],
      size: [1.04, 0.96, 0.34],
      rotation: [0, 0, 0],
      color: '#D59A45',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.1, segments: 6, flatShading: false },
    },
    {
      id: 'toast-head',
      shape: 'roundedBox',
      position: [0, 0.87, 0],
      size: [1.09, 0.28, 0.34],
      rotation: [0, 0, 0],
      color: '#D59A45',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.12, segments: 6, flatShading: false },
    },
    {
      id: 'golden-center',
      shape: 'roundedBox',
      position: [0, 0.52, -0.03],
      size: [0.82, 0.72, 0.32],
      rotation: [0, 0, 0],
      color: '#E9B85F',
      material: { roughness: 0.9, metalness: 0 },
      appearance: { radius: 0.09, segments: 6, flatShading: false },
    },
    {
      id: 'toast-mark-left',
      shape: 'roundedBox',
      position: [-0.22, 0.56, -0.22],
      size: [0.15, 0.48, 0.05],
      rotation: [0, 0, -0.08],
      color: '#B66E2E',
      material: { roughness: 0.92, metalness: 0 },
      appearance: { radius: 0.03, segments: 4, flatShading: false },
    },
    {
      id: 'toast-mark-right',
      shape: 'roundedBox',
      position: [0.22, 0.56, -0.22],
      size: [0.15, 0.48, 0.05],
      rotation: [0, 0, 0.08],
      color: '#B66E2E',
      material: { roughness: 0.92, metalness: 0 },
      appearance: { radius: 0.03, segments: 4, flatShading: false },
    },
  ],
  designNotes: [
    '食パンモデルと同じ一枚パンの外形を保ち、全体を焼き色に寄せて加工後と分かるようにする。',
    '中央を明るい黄金色にして、外側の濃い耳と焼き目を読みやすくする。',
    '前面の縦焼き目だけでトーストらしさを表現し、部品数を抑える。',
  ],
} as const satisfies FoodModelData;
